# bai tap 1

In [28]:
import numpy as np
A = np.eye(3,3, -1)
B = np.linalg.matrix_power(A,3)
I = np.eye(3,3)
K = np.matmul(I - A, I + A + np.linalg.matrix_power(A,2))

# Bai tap 2

In [8]:
a = np.array([[0.4,0.2,0.3],[0.3,0.6,0.3],[0.3,0.2,0.4]]) 
k = 10
for i in range(k):
    print(np.linalg.matrix_power(a,i))
    
print("=============================================")
a = np.array([[0,0.2,0.3],[0.1,0.6,0.3],[0.9,0.2,0.4]]) 
k = 10
for i in range(k):
    print(np.linalg.matrix_power(a,i))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.4 0.2 0.3]
 [0.3 0.6 0.3]
 [0.3 0.2 0.4]]
[[0.31 0.26 0.3 ]
 [0.39 0.48 0.39]
 [0.3  0.26 0.31]]
[[0.292 0.278 0.291]
 [0.417 0.444 0.417]
 [0.291 0.278 0.292]]
[[0.2875 0.2834 0.2874]
 [0.4251 0.4332 0.4251]
 [0.2874 0.2834 0.2875]]
[[0.28624 0.28502 0.28623]
 [0.42753 0.42996 0.42753]
 [0.28623 0.28502 0.28624]]
[[0.285871 0.285506 0.28587 ]
 [0.428259 0.428988 0.428259]
 [0.28587  0.285506 0.285871]]
[[0.2857612 0.2856518 0.2857611]
 [0.4284777 0.4286964 0.4284777]
 [0.2857611 0.2856518 0.2857612]]
[[0.28572835 0.28569554 0.28572834]
 [0.42854331 0.42860892 0.42854331]
 [0.28572834 0.28569554 0.28572835]]
[[0.2857185  0.28570866 0.2857185 ]
 [0.42856299 0.42858268 0.42856299]
 [0.2857185  0.28570866 0.2857185 ]]


# bai tap 3

In [2]:
import numpy as np
a = np.array([[1, 0, -1],[2,1,1],[0, 0, 2]]) 
k = 100
def giaiThua(n):
    if n == 0:
        return 1
    return n * giaiThua(n - 1)

result = 0
for i in range(k):
    result = result + 1/giaiThua(i) * np.linalg.matrix_power(a,i)
    #print(1/giaiThua(i) * np.linalg.matrix_power(a,i))
    
print(result)

[[ 2.71828183  0.         -4.67077427]
 [ 5.43656366  2.71828183  0.76578939]
 [ 0.          0.          7.3890561 ]]


## bai tap 4

In [24]:
import numpy as np
a = np.array([[1, 0, -1],[2,1,1],[0, 0, 2]]) 
b = a.copy()
for i in range(len(a)):
    for j in range(len(a[i])):
        b_temp = np.delete(a, i, 0)
        b_temp = np.delete(b_temp, j, 1)
        b[i][j] = (-1)**(i+j)*np.linalg.det(b_temp)
print(a)
print(b)

[[ 1  0 -1]
 [ 2  1  1]
 [ 0  0  2]]
[[ 2 -4  0]
 [ 0  2  0]
 [ 1 -2  1]]


# bai tap 5

In [19]:
import numpy as np
def matrix_factor_1(R, P, Q, K, steps = 5000, alpha = 0.0002, lamda = 1):
    Q = Q.T
    for steps in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:], Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - lamda * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - lamda * Q[k][j])
        eR = np.dot(P, Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:], Q[:,j]),2)
        if e < 0.0001:
            break
    return P, Q.T
                        
        

array([[ 1,  0, -1],
       [ 2,  1,  1],
       [ 0,  0,  2]])